--funcioens CAST y CONVERT en SQL Server son las de conversion de tipos de datos

--CAST FUNCION GENERICA CONVIERTE UN TIPO DE DATO A OTRO TIPO DE DATO SIEMPRE CUANDO TENGAN RELACION

--CONVERT FUNCION ESPECIFICA DE SQL SERVER PARA CONVERTIR TIPOS DE DATOS